onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /m1_test/uut/TH_1S
add wave -noupdate /m1_test/uut/ex_clk_50m
add wave -noupdate /m1_test/uut/rst_key
add wave -noupdate /m1_test/uut/gpio_in0
add wave -noupdate /m1_test/uut/gpio_in1
add wave -noupdate /m1_test/uut/LED
add wave -noupdate /m1_test/uut/RX
add wave -noupdate /m1_test/uut/TX
add wave -noupdate /m1_test/uut/spi0_clk
add wave -noupdate /m1_test/uut/spi0_cs
add wave -noupdate /m1_test/uut/spi0_mosi
add wave -noupdate /m1_test/uut/spi0_miso
add wave -noupdate /m1_test/uut/i2c0_sck
add wave -noupdate /m1_test/uut/i2c0_sda
add wave -noupdate /m1_test/uut/pad_loop_in
add wave -noupdate /m1_test/uut/pad_loop_in_h
add wave -noupdate /m1_test/uut/pad_rstn_ch0
add wave -noupdate /m1_test/uut/pad_ddr_clk_w
add wave -noupdate /m1_test/uut/pad_ddr_clkn_w
add wave -noupdate /m1_test/uut/pad_csn_ch0
add wave -noupdate /m1_test/uut/pad_addr_ch0
add wave -noupdate /m1_test/uut/pad_dq_ch0
add wave -noupdate /m1_test/uut/pad_dqs_ch0
add wave -noupdate /m1_test/uut/pad_dqsn_ch0
add wave -noupdate /m1_test/uut/pad_dm_rdqs_ch0
add wave -noupdate /m1_test/uut/pad_cke_ch0
add wave -noupdate /m1_test/uut/pad_odt_ch0
add wave -noupdate /m1_test/uut/pad_rasn_ch0
add wave -noupdate /m1_test/uut/pad_casn_ch0
add wave -noupdate /m1_test/uut/pad_wen_ch0
add wave -noupdate /m1_test/uut/pad_ba_ch0
add wave -noupdate /m1_test/uut/pad_loop_out
add wave -noupdate /m1_test/uut/pad_loop_out_h
add wave -noupdate /m1_test/uut/rx_clki
add wave -noupdate /m1_test/uut/phy_rx_dv
add wave -noupdate /m1_test/uut/phy_rxd0
add wave -noupdate /m1_test/uut/phy_rxd1
add wave -noupdate /m1_test/uut/phy_rxd2
add wave -noupdate /m1_test/uut/phy_rxd3
add wave -noupdate /m1_test/uut/l0_sgmii_clk_shft
add wave -noupdate /m1_test/uut/phy_tx_en
add wave -noupdate /m1_test/uut/phy_txd0
add wave -noupdate /m1_test/uut/phy_txd1
add wave -noupdate /m1_test/uut/phy_txd2
add wave -noupdate /m1_test/uut/phy_txd3
add wave -noupdate /m1_test/uut/cnt
add wave -noupdate /m1_test/uut/heart_beat_led
add wave -noupdate /m1_test/uut/HCLK
add wave -noupdate /m1_test/uut/HREADYOUT
add wave -noupdate /m1_test/uut/HRESP
add wave -noupdate /m1_test/uut/HRDATA
add wave -noupdate /m1_test/uut/HSEL
add wave -noupdate /m1_test/uut/HTRANS
add wave -noupdate /m1_test/uut/HBURST
add wave -noupdate /m1_test/uut/HPROT
add wave -noupdate /m1_test/uut/HSIZE
add wave -noupdate /m1_test/uut/HWRITE
add wave -noupdate /m1_test/uut/HMASTLOCK
add wave -noupdate /m1_test/uut/HADDR
add wave -noupdate /m1_test/uut/HWDATA
add wave -noupdate /m1_test/uut/HREADY
add wave -noupdate /m1_test/uut/HRDATAmux
add wave -noupdate /m1_test/uut/PADDR
add wave -noupdate /m1_test/uut/PWRITE
add wave -noupdate /m1_test/uut/PWDATA
add wave -noupdate /m1_test/uut/PENABLE
add wave -noupdate /m1_test/uut/PSEL
add wave -noupdate /m1_test/uut/PRDATA
add wave -noupdate /m1_test/uut/PREADY
add wave -noupdate /m1_test/uut/PSLVERR
add wave -noupdate /m1_test/uut/p0_in
add wave -noupdate /m1_test/uut/p0_out
add wave -noupdate /m1_test/uut/p0_outen
add wave -noupdate /m1_test/uut/p0_altfunc
add wave -noupdate /m1_test/uut/watchdog_reset
add wave -noupdate /m1_test/uut/wdata
add wave -noupdate /m1_test/uut/waddr
add wave -noupdate /m1_test/uut/w_en
add wave -noupdate /m1_test/uut/rdata
add wave -noupdate /m1_test/uut/raddr
add wave -noupdate /m1_test/uut/r_en
add wave -noupdate /m1_test/uut/mem_cs
add wave -noupdate /m1_test/uut/tsmac_tdata
add wave -noupdate /m1_test/uut/tsmac_tstart
add wave -noupdate /m1_test/uut/tsmac_tpnd
add wave -noupdate /m1_test/uut/tsmac_tlast
add wave -noupdate /m1_test/uut/tsmac_rdata
add wave -noupdate /m1_test/uut/tsmac_rvalid
add wave -noupdate /m1_test/uut/tsmac_rlast
add wave -noupdate /m1_test/uut/pll_pclk
add wave -noupdate /m1_test/uut/ddr_pll_lock
add wave -noupdate /m1_test/uut/ddrphy_rst_done
add wave -noupdate /m1_test/uut/ddrc_init_done
add wave -noupdate /m1_test/uut/aclk_mux
add wave -noupdate /m1_test/uut/awaddr_mux
add wave -noupdate /m1_test/uut/awlen_mux
add wave -noupdate /m1_test/uut/awvalid_mux
add wave -noupdate /m1_test/uut/awready_mux
add wave -noupdate /m1_test/uut/wdata_mux
add wave -noupdate /m1_test/uut/wstrb_mux
add wave -noupdate /m1_test/uut/wlast_mux
add wave -noupdate /m1_test/uut/wvalid_mux
add wave -noupdate /m1_test/uut/wready_mux
add wave -noupdate /m1_test/uut/araddr_mux
add wave -noupdate /m1_test/uut/arlen_mux
add wave -noupdate /m1_test/uut/arvalid_mux
add wave -noupdate /m1_test/uut/arready_mux
add wave -noupdate /m1_test/uut/rdata_mux
add wave -noupdate /m1_test/uut/rlast_mux
add wave -noupdate /m1_test/uut/rvalid_mux
add wave -noupdate /m1_test/uut/rready_mux
add wave -noupdate /m1_test/uut/aclk_1
add wave -noupdate /m1_test/uut/awaddr_1
add wave -noupdate /m1_test/uut/awvalid_1
add wave -noupdate /m1_test/uut/awready_1
add wave -noupdate /m1_test/uut/wdata_1
add wave -noupdate /m1_test/uut/wlast_1
add wave -noupdate /m1_test/uut/wvalid_1
add wave -noupdate /m1_test/uut/wready_1
add wave -noupdate /m1_test/uut/araddr_1
add wave -noupdate /m1_test/uut/arvalid_1
add wave -noupdate /m1_test/uut/arready_1
add wave -noupdate /m1_test/uut/rdata_1
add wave -noupdate /m1_test/uut/rlast_1
add wave -noupdate /m1_test/uut/rvalid_1
add wave -noupdate /m1_test/uut/rready_1
add wave -noupdate /m1_test/uut/tsmac_phy_pselx
add wave -noupdate /m1_test/uut/tsmac_phy_pwrite
add wave -noupdate /m1_test/uut/tsmac_phy_penable
add wave -noupdate /m1_test/uut/tsmac_phy_paddr
add wave -noupdate /m1_test/uut/tsmac_phy_pwdata
add wave -noupdate /m1_test/uut/tsmac_phy_mdo
add wave -noupdate /m1_test/uut/tsmac_phy_mdoen
add wave -noupdate /m1_test/uut/tsmac_phy_mdi
add wave -noupdate /m1_test/uut/tsmac_phy_mdio
add wave -noupdate /m1_test/uut/phy_txd
add wave -noupdate /m1_test/uut/phy_rxd
add wave -noupdate /m1_test/uut/m1_tdata
add wave -noupdate /m1_test/uut/m1_tstart
add wave -noupdate /m1_test/uut/m1_tpnd
add wave -noupdate /m1_test/uut/m1_tlast
add wave -noupdate /m1_test/uut/ethernet_fifo_rd_data
add wave -noupdate /m1_test/uut/tsmac_fifo_wr_data
add wave -noupdate /m1_test/uut/HREADYOUT_udp
add wave -noupdate /m1_test/uut/HRESP_udp
add wave -noupdate /m1_test/uut/HRDATA_udp
add wave -noupdate /m1_test/uut/udp_tdata
add wave -noupdate /m1_test/uut/udp_tstart
add wave -noupdate /m1_test/uut/udp_tpnd
add wave -noupdate /m1_test/uut/udp_tlast
add wave -noupdate /m1_test/uut/udp_cs
add wave -noupdate /m1_test/uut/DBGRESETn
add wave -noupdate /m1_test/uut/SYSRESETREQ
add wave -noupdate /m1_test/uut/SYSRESETn
add wave -noupdate /m1_test/uut/pad_nRST
add wave -noupdate /m1_test/uut/spi0_cs_0
add wave -noupdate /m1_test/uut/scl_pad_i
add wave -noupdate /m1_test/uut/scl_pad_o
add wave -noupdate /m1_test/uut/sda_pad_i
add wave -noupdate /m1_test/uut/sda_pad_o
add wave -noupdate /m1_test/uut/pad_nTRST
add wave -noupdate /m1_test/uut/pad_TCK
add wave -noupdate /m1_test/uut/pad_TMS
add wave -noupdate /m1_test/uut/pad_TDI
add wave -noupdate /m1_test/uut/pad_TDO
add wave -noupdate /m1_test/uut/HSEL_temp
add wave -noupdate /m1_test/uut/test_datai
add wave -noupdate /m1_test/uut/test_dbusy
add wave -noupdate /m1_test/uut/dready
add wave -noupdate /m1_test/uut/a_wr_en
add wave -noupdate /m1_test/uut/rdata0
add wave -noupdate /m1_test/uut/ddrc_pll_lock
add wave -noupdate /m1_test/uut/phy_rst_n
add wave -noupdate /m1_test/uut/pado
add wave -noupdate /m1_test/uut/padt
add wave -noupdate /m1_test/uut/rx_clki_shft_bufg
add wave -noupdate /m1_test/uut/rx_clki_clkbufg
add wave -noupdate /m1_test/uut/PSEL_temp
add wave -noupdate /m1_test/uut/PENABLE_temp
add wave -noupdate /m1_test/uut/tsmac_phy_mdc
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/ARM_CMSDK_APB_UART_PID4
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/ARM_CMSDK_APB_UART_PID5
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/ARM_CMSDK_APB_UART_PID6
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/ARM_CMSDK_APB_UART_PID7
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/ARM_CMSDK_APB_UART_PID0
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/ARM_CMSDK_APB_UART_PID1
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/ARM_CMSDK_APB_UART_PID2
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/ARM_CMSDK_APB_UART_PID3
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/ARM_CMSDK_APB_UART_CID0
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/ARM_CMSDK_APB_UART_CID1
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/ARM_CMSDK_APB_UART_CID2
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/ARM_CMSDK_APB_UART_CID3
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/PCLK
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/PCLKG
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/PRESETn
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/PSEL
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/PADDR
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/PENABLE
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/PWRITE
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/PWDATA
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/ECOREVNUM
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/PRDATA
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/PREADY
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/PSLVERR
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/RXD
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/TXD
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/TXEN
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/BAUDTICK
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/TXINT
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/RXINT
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/TXOVRINT
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/RXOVRINT
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/UARTINT
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/read_enable
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/write_enable
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/write_enable00
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/write_enable04
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/write_enable08
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/write_enable0c
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/write_enable10
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/read_mux_byte0
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/read_mux_byte0_reg
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/read_mux_word
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/pid3_value
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/reg_ctrl
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/reg_tx_buf
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/reg_rx_buf
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/reg_baud_div
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/reg_baud_cntr_i
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/nxt_baud_cntr_i
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/reg_baud_cntr_f
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/nxt_baud_cntr_f
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/mapped_cntr_f
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/reg_baud_tick
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/baud_updated
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/reload_i
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/reload_f
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/baud_div_en
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/uart_status
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/reg_rx_overrun
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/rx_overrun
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/reg_tx_overrun
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/tx_overrun
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/nxt_rx_overrun
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/nxt_tx_overrun
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/reg_txintr
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/reg_rxintr
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/tx_overflow_intr
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/rx_overflow_intr
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/intr_state
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/intr_stat_set
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/intr_stat_clear
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/tx_state
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/nxt_tx_state
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/tx_state_update
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/tx_state_inc
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/tx_tick_cnt
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/nxt_tx_tick_cnt
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/tx_shift_buf
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/nxt_tx_shift_buf
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/tx_buf_ctrl_shift
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/tx_buf_ctrl_load
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/tx_buf_full
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/reg_txd
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/nxt_txd
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/update_reg_txd
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/tx_buf_clear
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/rxd_sync_1
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/rxd_sync_2
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/rxd_lpf
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/nxt_rxd_lpf
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/rx_shift_in
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/rx_state
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/nxt_rx_state
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/rx_state_update
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/rx_tick_cnt
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/nxt_rx_tick_cnt
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/update_rx_tick_cnt
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/rx_state_inc
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/rx_shift_buf
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/nxt_rx_shift_buf
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/rx_buf_full
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/nxt_rx_buf_full
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/rxbuf_sample
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/rx_data_read
add wave -noupdate /m1_test/uut/u_integration_kit_dbg/u_apb_subsystem/gen_apb_uart_0/u_apb_uart_0/nxt_rx_buf
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {489852371880 fs} 0}
quietly wave cursor active 1
configure wave -namecolwidth 522
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits fs
update
WaveRestoreZoom {0 fs} {96695550 ps}
